### ISSUE TITLE
Play store version not compatible with the galaxy s7 edge (android 7)

### ISSUE THREAD

**Issue by nadakbar** [sitewaerts/android-document-viewer#3]
Hi the version in the play store called cleverdox is not compatible with my device. does not make it easy to test when it does not install

**Comment by regnete** [comment]
I checked it in the google play console again: All variants of "Samsung Galaxy S7 Edge" are compatible to the "cleverdox Viewer" App.

In the android manifest of the "cleverdox Viewer" App small screens are excluded:

      <supports-screens android:smallScreens="false"
                      android:normalScreens="true"
                      android:largeScreens="true"
                      android:xlargeScreens="true"
                      android:anyDensity="true"/>

Screen dimensions mentioned in google play console:
S7 : 1080 x 1920 (normal), 480dpi and 1440 x 2560 (normal), 640 dpi
Sony Experia Z3: 1080 x 1920 (normal), 480 dpi

https://developer.android.com/guide/topics/manifest/supports-screens-element.html

Seems as your S7 screen size is categorized as 'small' by google, so the latter rule wins. I don't know why they do this, but they obviously do.

Have you tried this approach to get maximum screen resolution after the andoird 7.0 (nougat) update?
1. Go to the Settings menu on the Galaxy S7 or S7 edge.
2. Scroll down to Display > tap on Change screen resolution.
3. In here, you can select: HD (1280 × 720), FHD (1920 × 1080), or WQHD (2560 × 1440)
4. Finally, tap on Apply to save the changes.
5. Now even when you restart your device, it will retain the screen resolution that you have chosen.
